# Install dependencies only when needed
FROM node:16-alpine AS deps

WORKDIR /usr/src/app


COPY . .

# Install dependencies in /app
RUN npm install

# Ensure port 3000 is accessible to our system
EXPOSE 3000

# Run yarn dev, as we would via the command line
CMD ["npm","run", "dev"]
