version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
#    container_name: web
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

